# This rule is not used by the project pondkeeper itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over gizmodata.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pondkeeper
    app.kubernetes.io/managed-by: kustomize
  name: duckdb-admin-role
rules:
- apiGroups:
  - gizmodata.com
  resources:
  - duckdbs
  verbs:
  - '*'
- apiGroups:
  - gizmodata.com
  resources:
  - duckdbs/status
  verbs:
  - get
