apiVersion: cache.duckdb.org/v1alpha1
kind: DuckDB
metadata:
  labels:
    app.kubernetes.io/name: pondkeeper
    app.kubernetes.io/managed-by: kustomize
  name: duckdb-sample
spec:
  # TODO(user): Add fields here
