{{- if .Values.rbacHelpers.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: pondkeeper
    name: pondkeeper-duckdb-editor-role
rules:
    - apiGroups:
        - gizmodata.com
      resources:
        - duckdbs
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - gizmodata.com
      resources:
        - duckdbs/status
      verbs:
        - get
{{- end }}
